CREATE DATABASE RRHH;

USE RRHH;

CREATE TABLE EMPLOYEE (
    ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    FIRST_NAME VARCHAR(20) NOT NULL, 
    LAST_NAME VARCHAR(20) NOT NULL, 
    DI VARCHAR(15) NOT NULL, 
    BIRTH_DATE DATE NOT NULL, 
    DEPARTMENT INTEGER NOT NULL, 
    HIRING_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SALARY INTEGER NOT NULL
);
