package ar.com.ada.backend12.employeeCrud.model;

public enum Department {
    SYSTEMS,
    HUMAN_RESOURCES,
    ACCOUNTING,
    CUSTOMER_SERVICE,
    PROJECT_MANAGER,
    UX_DESIGNER,
    UI_DESIGNER,
    BUSINESS_ANALYST,
    BACKEND_DEVELOPER,
    FRONTED_DEVELOPER,
    TESTER_QA,
    DATA_ANALYST,
    TEAM_LEAD,
    TEACH_LEAD,
    SCRUM_MASTER
}